name = "slyplayer-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "api.slyplayer.com/*", zone_name = "slyplayer.com" }
]

[vars]
BASE_URL = "https://api.slyplayer.com"
WEB_URL = "https://slyplayer.com"
JWT_SECRET = "slyplayer-jwt-secret-change-in-production-2024"
VPS_TRANSCODE_URL = "https://player.bastienbricout.com/api/transcode"
STRIPE_PRICE_STARTER = "price_1TJPk8CE0sI0qfx68i86Q9Y5"
STRIPE_PRICE_PRO = "price_1TJPk9CE0sI0qfx6HGPeBa84"
STRIPE_PRICE_BUSINESS = "price_1TJPkOCE0sI0qfx6cvJpuCOq"

[[d1_databases]]
binding = "DB"
database_name = "slyplayer-db"
database_id = "5aea023d-f257-41a4-9c5e-2dcadc36c6aa"

[[r2_buckets]]
binding = "R2"
bucket_name = "slyplayer-videos"
